<?php

include_once('embed_video_china.features.inc');

/**
* Implementation of hook_init().
*/
function embed_video_china_init() {
  drupal_add_css(drupal_get_path('module', 'embed_video_china') .'/embed_video_china.css');
}

/**
* Implementation of hook_help().
*/
function embed_video_china_help($path) {
  // Central help page content.
  if ($path == 'admin/help#embed_video_china') {
    $help = '<h3>'. t('Embedded Video (China)') .'</h3>';
    $help .= '<p>'. t("The Embedded Video section lets you add video from around the web.") .'</p>';
    $help .= '<p>'. t("To add videos, copy the click from a site like YouKu, Toudu or Ku6 and navigate to the video section and click the __Add video__ button.  Then click __Save__.") .'</p>';
    return $help;
  }

  // Contextual help content.
  if (context_isset('context', 'embed_videos_zh')) {
    if ($path == 'node/add/video_zh') {
      $help = '';
      $help .= '<h3>'. t('Video') .'</h3>';
      $help .= '<p>'. t("Post a video in this group from YouKu, Toudu, or Ku6. The video will be available in the Video gallery.") .'</p>';
      return $help;
    }
    else {
      $help = '<h3>'. t('Video') .'</h3>';
      $help .= '<p>'. t("Add video from sites like Youku, Toudou and Ku6 to your group.") .'</p>';
      return $help;
    }
  }
}